#!/usr/bin/env bash
# SessionStart hook: detect device identity + update device-session.md — 0 tokens
# Always exits 0 — never blocks session.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

DEVICE_FILE="$HOME/.wiki-device"
DEVICE_SESSION_MD="wiki/context/device-session.md"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M')"
DATE_ONLY="$(date '+%Y-%m-%d')"

# Detect device
OS="$(uname -s 2>/dev/null || echo 'Unknown')"
ARCH="$(uname -m 2>/dev/null || echo 'unknown')"
HOSTNAME_RAW="$(hostname 2>/dev/null || echo 'unknown')"
HOSTNAME_SHORT="${HOSTNAME_RAW%%.*}"

if [[ -f "$DEVICE_FILE" ]]; then
    DEVICE_NAME="$(tr -d '[:space:]' < "$DEVICE_FILE")"
    DETECT_METHOD="~/.wiki-device"
elif [[ "$OS" == "Darwin" ]]; then
    DEVICE_NAME="home-mac"
    DETECT_METHOD="auto:Darwin"
else
    IS_CONTAINER=0
    [[ -n "${CLAUDE_CODE_SESSION_ID:-}" ]] && IS_CONTAINER=1
    [[ "$HOSTNAME_SHORT" =~ ^[0-9a-f]{12,}$ ]] && IS_CONTAINER=1
    if [[ -f /proc/1/cgroup ]]; then
        grep -qE '(docker|kubepods|lxc|containerd)' /proc/1/cgroup 2>/dev/null && IS_CONTAINER=1
    fi
    if [[ "$IS_CONTAINER" -eq 1 ]]; then
        DEVICE_NAME="web-mobile"
        DETECT_METHOD="auto:container-linux"
    else
        DEVICE_NAME="work-pc"
        DETECT_METHOD="auto:persistent-linux"
    fi
fi

PLATFORM="${OS} ${ARCH}"
case "$DEVICE_NAME" in
    work-pc)    ICON="🖥️" ;;
    home-mac)   ICON="💻" ;;
    web-mobile) ICON="📱" ;;
    *)          ICON="🖥️" ;;
esac

echo "${ICON} Device: ${DEVICE_NAME} (${PLATFORM}, hostname: ${HOSTNAME_SHORT}, detect: ${DETECT_METHOD})" >&2

# Read existing history (keep last 9 rows; new row prepended = 10 total)
HISTORY_LINES=""
if [[ -f "$DEVICE_SESSION_MD" ]]; then
    HISTORY_LINES="$(grep '^| 20' "$DEVICE_SESSION_MD" 2>/dev/null | head -9 || true)"
fi

TMP_FILE="${DEVICE_SESSION_MD}.tmp.$$"

cat > "$TMP_FILE" << MDEOF
# Device Session

> Auto-generated by \`.claude/hooks/session-start-device.sh\` — do not edit manually
> Updated: ${TIMESTAMP}

## Current Session

| Field | Value |
|-------|-------|
| Device | **${DEVICE_NAME}** |
| Platform | ${PLATFORM} |
| Hostname | ${HOSTNAME_SHORT} |
| Detected via | ${DETECT_METHOD} |
| Session start | ${TIMESTAMP} |

## Session History (last 10)

| Date | Device | Platform | Hostname |
|------|--------|----------|----------|
| ${DATE_ONLY} | ${DEVICE_NAME} | ${PLATFORM} | ${HOSTNAME_SHORT} |
MDEOF

[[ -n "$HISTORY_LINES" ]] && printf '%s\n' "$HISTORY_LINES" >> "$TMP_FILE"

cat >> "$TMP_FILE" << 'MDEOF2'

## Setup Notes

- **work-pc**: `echo "work-pc" > ~/.wiki-device` on hospital Linux PC
- **home-mac**: `echo "home-mac" > ~/.wiki-device` on MacBook M1
- **web-mobile**: auto-detected (ephemeral container, no setup needed)
MDEOF2

mv "$TMP_FILE" "$DEVICE_SESSION_MD"
exit 0
