#!/usr/bin/env python3
"""Render a Phaser Scene TypeScript stub from asset-manifest payload JSON."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


def load_payload(target: str) -> dict[str, Any]:
    if target == "-":
        raw = sys.stdin.read()
    else:
        raw = Path(target).read_text(encoding="utf-8")
    data = json.loads(raw)
    if not isinstance(data, dict):
        raise ValueError("payload must be a JSON object")
    return data


def sanitize_identifier(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name).strip("_")
    return cleaned or "GeneratedAssetScene"


def lower_camel(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    parts = [part for part in parts if part]
    if not parts:
        return "generatedAssetScene"
    first = parts[0].lower()
    rest = [part[:1].upper() + part[1:] for part in parts[1:]]
    return "".join([first, *rest])


def js(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_scene_stub(
    payload: dict[str, Any],
    scene_name: str,
    scene_key: str,
    module_import: str,
) -> str:
    scene_name = sanitize_identifier(scene_name)
    scene_key_const = f"{lower_camel(scene_key)}SceneKey"
    preload = payload.get("preload") or []
    animations = payload.get("animations") or []
    preview_texture = preload[0]["key"] if preload else None
    preview_animation = animations[0]["key"] if animations else None

    lines = [
        "/* Auto-generated by scripts/game/build_phaser_scene_stub_ts.py */",
        'import Phaser from "phaser";',
        f'import {{ preloadPhaserAssets, registerPhaserAnimations }} from {js(module_import)};',
        "",
        f"export const {scene_key_const} = {js(scene_key)};",
        "",
        f"export class {scene_name} extends Phaser.Scene {{",
    ]

    if preview_texture:
        lines.append(f"  private readonly previewTextureKey = {js(preview_texture)};")
    if preview_animation:
        lines.append(f"  private readonly previewAnimationKey = {js(preview_animation)};")
    if preview_texture:
        lines.append("  private previewSprite?: Phaser.GameObjects.Sprite;")
    lines.extend(
        [
            "",
            "  constructor() {",
            f"    super({scene_key_const});",
            "  }",
            "",
            "  preload(): void {",
            "    preloadPhaserAssets(this);",
            "  }",
            "",
            "  create(): void {",
            "    registerPhaserAnimations(this);",
        ]
    )

    if preview_texture:
        lines.extend(
            [
                "    this.previewSprite = this.add.sprite(this.cameras.main.centerX, this.cameras.main.centerY, this.previewTextureKey);",
            ]
        )
        if preview_animation:
            lines.extend(
                [
                    "    this.previewSprite.play(this.previewAnimationKey);",
                ]
            )

    lines.extend(
        [
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render a Phaser Scene TypeScript stub from JSON payload.")
    parser.add_argument("target", help="JSON payload file, or '-' to read from stdin.")
    parser.add_argument("--scene-name", default="GeneratedAssetScene", help="TypeScript class name for the scene.")
    parser.add_argument("--scene-key", default="generated-asset-scene", help="Phaser scene key.")
    parser.add_argument("--module-import", default="./phaser_assets", help="Import path for preload/register helper module.")
    args = parser.parse_args(argv)

    payload = load_payload(args.target)
    print(
        render_scene_stub(
            payload,
            scene_name=args.scene_name,
            scene_key=args.scene_key,
            module_import=args.module_import,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
