#!/usr/bin/env python3
"""Render a TypeScript Phaser loader/animation module from manifest JSON."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


def load_payload(target: str) -> dict[str, Any]:
    if target == "-":
        raw = sys.stdin.read()
    else:
        raw = Path(target).read_text(encoding="utf-8")
    data = json.loads(raw)
    if not isinstance(data, dict):
        raise ValueError("payload must be a JSON object")
    return data


def sanitize_module_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name).strip("_")
    return cleaned or "phaser_assets"


def js(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_preload(preload: list[dict[str, Any]]) -> list[str]:
    lines = ["export function preloadPhaserAssets(scene: Phaser.Scene): void {"]
    if not preload:
        lines.append("  return;")
        lines.append("}")
        return lines

    for entry in preload:
        if entry.get("kind") != "spritesheet":
            continue
        frame_config = entry.get("frame_config") or {}
        lines.append(
            "  scene.load.spritesheet("
            f"{js(entry.get('key', ''))}, "
            f"{js(entry.get('path', ''))}, "
            "{ "
            f"frameWidth: {int(frame_config.get('frameWidth', 0))}, "
            f"frameHeight: {int(frame_config.get('frameHeight', 0))}"
            " }"
            ");"
        )
    lines.append("}")
    return lines


def render_animation(entry: dict[str, Any]) -> list[str]:
    key = entry.get("key", "")
    texture_key = entry.get("texture_key", "")
    start = int(entry.get("start", 0))
    end = int(entry.get("end", start))
    frame_rate = int(entry.get("frameRate", 10))
    repeat = int(entry.get("repeat", -1))
    return [
        f"  if (scene.anims.exists({js(key)})) {{",
        "    return;",
        "  }",
        "  scene.anims.create({",
        f"    key: {js(key)},",
        f"    frames: scene.anims.generateFrameNumbers({js(texture_key)}, {{ start: {start}, end: {end} }}),",
        f"    frameRate: {frame_rate},",
        f"    repeat: {repeat},",
        "  });",
    ]


def render_animations(animations: list[dict[str, Any]]) -> list[str]:
    lines = ["export function registerPhaserAnimations(scene: Phaser.Scene): void {"]
    if not animations:
        lines.append("  return;")
        lines.append("}")
        return lines

    for entry in animations:
        lines.extend(render_animation(entry))
    lines.append("}")
    return lines


def render_typescript(payload: dict[str, Any], module_name: str = "phaser_assets") -> str:
    module_name = sanitize_module_name(module_name)
    preload = payload.get("preload") or []
    animations = payload.get("animations") or []
    summary = payload.get("summary") or {}

    lines = [
        "/* Auto-generated by scripts/game/build_phaser_loader_ts.py */",
        'import type Phaser from "phaser";',
        "",
        f"export const {module_name}Summary = {json.dumps(summary, ensure_ascii=False, indent=2)} as const;",
        "",
        *render_preload(preload),
        "",
        *render_animations(animations),
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render a TypeScript Phaser loader module from JSON payload.")
    parser.add_argument("target", help="JSON payload file, or '-' to read from stdin.")
    parser.add_argument("--module-name", default="phaser_assets", help="Identifier prefix used for exported summary const.")
    args = parser.parse_args(argv)

    payload = load_payload(args.target)
    print(render_typescript(payload, module_name=args.module_name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
