#!/usr/bin/env python3
"""Normalize PixelLab animation frames for น้องซันเดย์ into clean, deterministic
per-action sequences + emit a TS module the Phaser scene can import.

PixelLab exports frames as `nong-sunday_animations_<action-desc>-<hash>_south_frame_NNN.png`.
This flattens them to `anim_clean/<action>_south_NNN.png` and writes
`src/phaser/playerAnims.ts` (action → ordered public paths + frameRate/repeat).
"""
from __future__ import annotations
import json
import os
import re
import shutil

PWQ = "/Users/aase7en/Desktop/sunday-estate-webapp/pixel-wealth-quest"
ANIM = f"{PWQ}/public/assets/character/nong-sunday/anim"
CLEAN = f"{PWQ}/public/assets/character/nong-sunday/anim_clean"
TS_OUT = f"{PWQ}/src/phaser/playerAnims.ts"

# action-description prefix → clean action key
ACTION_MAP = {
    "standing_still": "idle",
    "walking_moving": "walk",
    "running_fast": "run",
    "sitting_down": "sit",
    "lying_down": "lie",
    "eating_food": "eat",
    "crying_sadly": "cry",
}
FRAME_RATE = {"idle": 4, "walk": 10, "run": 12, "sit": 8, "lie": 8, "eat": 7, "cry": 6}
REPEAT = {"idle": -1, "walk": -1, "run": -1}  # loops; others play once (0)

os.makedirs(CLEAN, exist_ok=True)
for f in os.listdir(CLEAN):
    os.remove(os.path.join(CLEAN, f))

groups: dict[str, list[tuple[int, str]]] = {}
pat = re.compile(r"nong-sunday_animations_(.+?)_south_frame_(\d+)\.png")
for f in os.listdir(ANIM):
    m = pat.match(f)
    if not m:
        continue
    slug, num = m.group(1), int(m.group(2))
    action = next((v for k, v in ACTION_MAP.items() if slug.startswith(k)), None)
    if action:
        groups.setdefault(action, []).append((num, f))

anims: dict[str, list[str]] = {}
for action, items in groups.items():
    items.sort()
    paths = []
    for i, (_, f) in enumerate(items):
        dst = f"{action}_south_{i:03d}.png"
        shutil.copy(os.path.join(ANIM, f), os.path.join(CLEAN, dst))
        paths.append(f"assets/character/nong-sunday/anim_clean/{dst}")
    anims[action] = paths

lines = [
    "// AUTO-GENERATED by scripts/game/normalize_pwq_anims.py — do not edit by hand.",
    "// น้องซันเดย์ animations (PixelLab create-character-v3 + animate-character, south-facing).",
    "export interface PlayerAnimDef { key: string; frames: string[]; frameRate: number; repeat: number }",
    "export const PLAYER_ANIMS: Record<string, PlayerAnimDef> = {",
]
for a, paths in sorted(anims.items()):
    lines.append(
        f"  {a}: {{ key: '{a}', frames: {json.dumps(paths)}, "
        f"frameRate: {FRAME_RATE.get(a, 8)}, repeat: {REPEAT.get(a, 0)} }},"
    )
lines += ["}", "export type PlayerAction = keyof typeof PLAYER_ANIMS", ""]
with open(TS_OUT, "w") as fh:
    fh.write("\n".join(lines))

print(json.dumps({a: len(p) for a, p in sorted(anims.items())}, indent=0))
print("wrote", TS_OUT)
