#!/usr/bin/env python3
"""Normalize PixelLab animation frames for Pixel Wealth Quest.

PixelLab exports frames like:

    nong-sunday_animations_<action-desc>-<hash>_south_frame_NNN.png

This script copies those files into deterministic per-action sequences:

    public/assets/character/nong-sunday/anim_clean/<action>_south_NNN.png

and emits `src/phaser/playerAnims.ts` for Phaser preload/register code. Walk
animations can contain all PixelLab directions; they map onto PWQ's Dir8 names.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
from pathlib import Path


ACTION_ORDER = ["idle", "walk", "run", "sit", "lie", "eat", "cry", "water", "hoe", "harvest"]
MOVE_ACTION_ORDER = ["walk", "run"]
WALK_LEFT_USES_SW = True
DIRECTIONAL_RUN_USES_WALK = True
ACTION_MAP = {
    "standing_still": "idle",
    "walking_moving": "walk",
    "running_fast": "run",
    "sitting_down": "sit",
    "lying_down": "lie",
    "eating_food": "eat",
    "crying_sadly": "cry",
    "watering_plants": "water",
    "hoeing_soil": "hoe",
    # PixelLab slugs come from the free-text action description, so match the
    # leading verb only ("harvesting_a_crop_with_a_sickle_…").
    "harvesting": "harvest",
}
FRAME_RATE = {
    "idle": 4,
    "walk": 10,
    "run": 12,
    "sit": 8,
    "lie": 8,
    "eat": 7,
    "cry": 6,
    "water": 8,
    "hoe": 8,
    "harvest": 8,
}
REPEAT = {"idle": -1, "walk": -1, "run": -1}
PUBLIC_BASE = "assets/character/nong-sunday/anim_clean"
PIXELLAB_DIRECTIONS = ["south", "south-east", "east", "north-east", "north", "north-west", "west", "south-west"]
PIXELLAB_TO_DIR8 = {
    "south": "front",
    "south-east": "front_right",
    "east": "right",
    "north-east": "back_right",
    "north": "back",
    "north-west": "back_left",
    "west": "left",
    "south-west": "front_left",
}
DIR8_ORDER = ["front", "front_right", "right", "back_right", "back", "back_left", "left", "front_left"]
FRAME_RE = re.compile(
    rf"nong-sunday_animations_(.+?)_({'|'.join(map(re.escape, PIXELLAB_DIRECTIONS))})_frame_(\d+)\.png$"
)


def default_pwq_root() -> Path:
    """Resolve the sibling product repo without hardcoding a personal path."""
    if os.environ.get("PWQ_ROOT"):
        return Path(os.environ["PWQ_ROOT"]).expanduser()

    awiki_root = Path(__file__).resolve().parents[2]
    for sibling in awiki_root.parent.glob("*/pixel-wealth-quest"):
        if sibling.is_dir():
            return sibling
    return Path.cwd()


def action_for_slug(slug: str) -> str | None:
    return next((action for prefix, action in ACTION_MAP.items() if slug.startswith(prefix)), None)


def best_export_for_action(
    action: str, exports: dict[str, dict[str, list[tuple[int, Path]]]]
) -> dict[str, list[tuple[int, Path]]]:
    if not exports:
        return {}

    def score(item: tuple[str, dict[str, list[tuple[int, Path]]]]) -> tuple[int, int, str]:
        slug, by_direction = item
        direction_count = len([direction for direction, frames in by_direction.items() if frames])
        frame_count = sum(len(frames) for frames in by_direction.values())
        return (direction_count if action in MOVE_ACTION_ORDER else 0, frame_count, slug)

    return max(exports.items(), key=score)[1]


def render_player_anims_ts(anims: dict[str, list[str]], move_anims: dict[str, dict[str, list[str]]]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/game/normalize_pwq_anims.py. Do not edit by hand.",
        "// Nong Sunday animations from PixelLab create-character-v3 + animate-character.",
        "import type Phaser from 'phaser'",
        "import type { Dir8 } from '../types/domain'",
        "",
        f"export const PLAYER_ANIM_ACTIONS = {json.dumps(ACTION_ORDER)} as const",
        "export type PlayerAction = (typeof PLAYER_ANIM_ACTIONS)[number]",
        f"export const PLAYER_MOVE_ACTIONS = {json.dumps(MOVE_ACTION_ORDER)} as const",
        "export type PlayerMoveAction = (typeof PLAYER_MOVE_ACTIONS)[number]",
        "export interface PlayerAnimDef { key: string; frames: readonly string[]; frameRate: number; repeat: number }",
        "",
        "export const PLAYER_ANIMS: Record<PlayerAction, PlayerAnimDef> = {",
    ]
    for action in ACTION_ORDER:
        paths = anims.get(action, [])
        lines.append(
            f"  {action}: {{ key: 'pwq_player_{action}_front', frames: {json.dumps(paths)}, "
            f"frameRate: {FRAME_RATE.get(action, 8)}, repeat: {REPEAT.get(action, 0)} }},"
        )
    lines += ["}", ""]
    lines += ["export const PLAYER_MOVE_ANIMS: Record<PlayerMoveAction, Record<Dir8, PlayerAnimDef>> = {"]
    for action in MOVE_ACTION_ORDER:
        lines.append(f"  {action}: {{")
        fallback = move_anims.get(action, {}).get("front", anims.get(action, []))
        for dir8 in DIR8_ORDER:
            paths = move_anims.get(action, {}).get(dir8, fallback)
            lines.append(
                f"    {dir8}: {{ key: 'pwq_player_{action}_{dir8}', frames: {json.dumps(paths)}, "
                f"frameRate: {FRAME_RATE.get(action, 8)}, repeat: {REPEAT.get(action, -1)} }},"
            )
        lines.append("  },")
    lines += [
        "}",
        "",
        "export function playerAnimFrameKey(action: PlayerAction, index: number, dir?: Dir8): string {",
        "  const suffix = dir ? `${dir}_${String(index).padStart(3, '0')}` : String(index).padStart(3, '0')",
        "  return `pwq_player_anim_${action}_${suffix}`",
        "}",
        "",
        "export function playerMoveAnimKey(action: PlayerMoveAction, dir: Dir8): string {",
        "  return PLAYER_MOVE_ANIMS[action][dir].key",
        "}",
        "",
        "export function preloadPlayerAnimations(scene: Phaser.Scene): void {",
        "  for (const action of PLAYER_ANIM_ACTIONS) {",
        "    const def = PLAYER_ANIMS[action]",
        "    def.frames.forEach((path, index) => scene.load.image(playerAnimFrameKey(action, index), path))",
        "  }",
        "  for (const action of PLAYER_MOVE_ACTIONS) {",
        "    for (const dir of Object.keys(PLAYER_MOVE_ANIMS[action]) as Dir8[]) {",
        "      const def = PLAYER_MOVE_ANIMS[action][dir]",
        "      def.frames.forEach((path, index) => scene.load.image(playerAnimFrameKey(action, index, dir), path))",
        "    }",
        "  }",
        "}",
        "",
        "export function registerPlayerAnimations(scene: Phaser.Scene): void {",
        "  for (const action of PLAYER_ANIM_ACTIONS) {",
        "    const def = PLAYER_ANIMS[action]",
        "    if (scene.anims.exists(def.key)) continue",
        "    scene.anims.create({",
        "      key: def.key,",
        "      frames: def.frames.map((_, index) => ({ key: playerAnimFrameKey(action, index) })),",
        "      frameRate: def.frameRate,",
        "      repeat: def.repeat,",
        "    })",
        "  }",
        "  for (const action of PLAYER_MOVE_ACTIONS) {",
        "    for (const dir of Object.keys(PLAYER_MOVE_ANIMS[action]) as Dir8[]) {",
        "      const def = PLAYER_MOVE_ANIMS[action][dir]",
        "      if (scene.anims.exists(def.key)) continue",
        "      scene.anims.create({",
        "        key: def.key,",
        "        frames: def.frames.map((_, index) => ({ key: playerAnimFrameKey(action, index, dir) })),",
        "        frameRate: def.frameRate,",
        "        repeat: def.repeat,",
        "      })",
        "    }",
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def normalize_animation_frames(pwq_root: str | Path) -> dict[str, int]:
    root = Path(pwq_root).expanduser().resolve()
    anim_dir = root / "public" / "assets" / "character" / "nong-sunday" / "anim"
    clean_dir = root / "public" / "assets" / "character" / "nong-sunday" / "anim_clean"
    ts_out = root / "src" / "phaser" / "playerAnims.ts"

    if not anim_dir.exists():
        raise FileNotFoundError(f"animation source dir not found: {anim_dir}")

    clean_dir.mkdir(parents=True, exist_ok=True)
    for old in clean_dir.glob("*.png"):
        old.unlink()

    groups: dict[str, dict[str, dict[str, list[tuple[int, Path]]]]] = {}
    for path in sorted(anim_dir.glob("*.png")):
        match = FRAME_RE.match(path.name)
        if not match:
            continue
        slug, direction, frame_no = match.group(1), match.group(2), int(match.group(3))
        action = action_for_slug(slug)
        if action:
            groups.setdefault(action, {}).setdefault(slug, {}).setdefault(direction, []).append((frame_no, path))

    anims: dict[str, list[str]] = {action: [] for action in ACTION_ORDER}
    move_anims: dict[str, dict[str, list[str]]] = {action: {} for action in MOVE_ACTION_ORDER}
    for action in ACTION_ORDER:
        selected = best_export_for_action(action, groups.get(action, {}))
        items = sorted(selected.get("south", []))
        for index, (_, src) in enumerate(items):
            dst_name = f"{action}_south_{index:03d}.png"
            shutil.copyfile(src, clean_dir / dst_name)
            anims[action].append(f"{PUBLIC_BASE}/{dst_name}")
        if action in MOVE_ACTION_ORDER:
            for pixel_dir, dir8 in PIXELLAB_TO_DIR8.items():
                dir_items = sorted(selected.get(pixel_dir, []))
                for index, (_, src) in enumerate(dir_items):
                    dst_name = f"{action}_{pixel_dir}_{index:03d}.png"
                    shutil.copyfile(src, clean_dir / dst_name)
                    move_anims[action].setdefault(dir8, []).append(f"{PUBLIC_BASE}/{dst_name}")
            if action == "walk" and WALK_LEFT_USES_SW and move_anims[action].get("front_left"):
                move_anims[action]["left"] = list(move_anims[action]["front_left"])

    if DIRECTIONAL_RUN_USES_WALK and move_anims["run"].get("front"):
        for dir8, paths in move_anims["walk"].items():
            move_anims["run"].setdefault(dir8, list(paths))

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    ts_out.write_text(render_player_anims_ts(anims, move_anims), encoding="utf-8")
    counts: dict[str, int] = {}
    for action in ACTION_ORDER:
        if action in MOVE_ACTION_ORDER and move_anims.get(action):
            counts[action] = sum(len(paths) for paths in move_anims[action].values())
        elif anims[action]:
            counts[action] = len(anims[action])
    return counts


def main() -> int:
    parser = argparse.ArgumentParser(description="Normalize Nong Sunday PixelLab animation frames")
    parser.add_argument("--pwq-root", default=None, help="Path to <product-repo>/pixel-wealth-quest")
    args = parser.parse_args()

    root = Path(args.pwq_root).expanduser() if args.pwq_root else default_pwq_root()
    counts = normalize_animation_frames(root)
    print(json.dumps(counts, ensure_ascii=False, indent=2))
    print(f"wrote {Path(root).expanduser().resolve() / 'src' / 'phaser' / 'playerAnims.ts'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
