#!/usr/bin/env python3
"""Normalize PixelLab animation frames for Pixel Wealth Quest.

PixelLab exports frames like:

    nong-sunday_animations_<action-desc>-<hash>_south_frame_NNN.png

This script copies those files into deterministic per-action sequences:

    public/assets/character/nong-sunday/anim_clean/<action>_south_NNN.png

and emits `src/phaser/playerAnims.ts` for Phaser preload/register code.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
from pathlib import Path


ACTION_ORDER = ["idle", "walk", "run", "sit", "lie", "eat", "cry"]
ACTION_MAP = {
    "standing_still": "idle",
    "walking_moving": "walk",
    "running_fast": "run",
    "sitting_down": "sit",
    "lying_down": "lie",
    "eating_food": "eat",
    "crying_sadly": "cry",
}
FRAME_RATE = {"idle": 4, "walk": 10, "run": 12, "sit": 8, "lie": 8, "eat": 7, "cry": 6}
REPEAT = {"idle": -1, "walk": -1, "run": -1}
PUBLIC_BASE = "assets/character/nong-sunday/anim_clean"
FRAME_RE = re.compile(r"nong-sunday_animations_(.+?)_south_frame_(\d+)\.png$")


def default_pwq_root() -> Path:
    """Resolve the sibling product repo without hardcoding a personal path."""
    if os.environ.get("PWQ_ROOT"):
        return Path(os.environ["PWQ_ROOT"]).expanduser()

    awiki_root = Path(__file__).resolve().parents[2]
    sibling = awiki_root.parent / "sunday-estate-webapp" / "pixel-wealth-quest"
    if sibling.exists():
        return sibling
    return Path.cwd()


def action_for_slug(slug: str) -> str | None:
    return next((action for prefix, action in ACTION_MAP.items() if slug.startswith(prefix)), None)


def render_player_anims_ts(anims: dict[str, list[str]]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/game/normalize_pwq_anims.py. Do not edit by hand.",
        "// Nong Sunday animations from PixelLab create-character-v3 + animate-character.",
        "import type Phaser from 'phaser'",
        "",
        f"export const PLAYER_ANIM_ACTIONS = {json.dumps(ACTION_ORDER)} as const",
        "export type PlayerAction = (typeof PLAYER_ANIM_ACTIONS)[number]",
        "export interface PlayerAnimDef { key: string; frames: readonly string[]; frameRate: number; repeat: number }",
        "",
        "export const PLAYER_ANIMS: Record<PlayerAction, PlayerAnimDef> = {",
    ]
    for action in ACTION_ORDER:
        paths = anims.get(action, [])
        lines.append(
            f"  {action}: {{ key: 'pwq_player_{action}_front', frames: {json.dumps(paths)}, "
            f"frameRate: {FRAME_RATE.get(action, 8)}, repeat: {REPEAT.get(action, 0)} }},"
        )
    lines += [
        "}",
        "",
        "export function playerAnimFrameKey(action: PlayerAction, index: number): string {",
        "  return `pwq_player_anim_${action}_${String(index).padStart(3, '0')}`",
        "}",
        "",
        "export function preloadPlayerAnimations(scene: Phaser.Scene): void {",
        "  for (const action of PLAYER_ANIM_ACTIONS) {",
        "    const def = PLAYER_ANIMS[action]",
        "    def.frames.forEach((path, index) => scene.load.image(playerAnimFrameKey(action, index), path))",
        "  }",
        "}",
        "",
        "export function registerPlayerAnimations(scene: Phaser.Scene): void {",
        "  for (const action of PLAYER_ANIM_ACTIONS) {",
        "    const def = PLAYER_ANIMS[action]",
        "    if (scene.anims.exists(def.key)) continue",
        "    scene.anims.create({",
        "      key: def.key,",
        "      frames: def.frames.map((_, index) => ({ key: playerAnimFrameKey(action, index) })),",
        "      frameRate: def.frameRate,",
        "      repeat: def.repeat,",
        "    })",
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def normalize_animation_frames(pwq_root: str | Path) -> dict[str, int]:
    root = Path(pwq_root).expanduser().resolve()
    anim_dir = root / "public" / "assets" / "character" / "nong-sunday" / "anim"
    clean_dir = root / "public" / "assets" / "character" / "nong-sunday" / "anim_clean"
    ts_out = root / "src" / "phaser" / "playerAnims.ts"

    if not anim_dir.exists():
        raise FileNotFoundError(f"animation source dir not found: {anim_dir}")

    clean_dir.mkdir(parents=True, exist_ok=True)
    for old in clean_dir.glob("*.png"):
        old.unlink()

    groups: dict[str, list[tuple[int, Path]]] = {}
    for path in sorted(anim_dir.glob("*.png")):
        match = FRAME_RE.match(path.name)
        if not match:
            continue
        slug, frame_no = match.group(1), int(match.group(2))
        action = action_for_slug(slug)
        if action:
            groups.setdefault(action, []).append((frame_no, path))

    anims: dict[str, list[str]] = {action: [] for action in ACTION_ORDER}
    for action in ACTION_ORDER:
        items = sorted(groups.get(action, []))
        for index, (_, src) in enumerate(items):
            dst_name = f"{action}_south_{index:03d}.png"
            shutil.copyfile(src, clean_dir / dst_name)
            anims[action].append(f"{PUBLIC_BASE}/{dst_name}")

    ts_out.parent.mkdir(parents=True, exist_ok=True)
    ts_out.write_text(render_player_anims_ts(anims), encoding="utf-8")
    return {action: len(anims[action]) for action in ACTION_ORDER if anims[action]}


def main() -> int:
    parser = argparse.ArgumentParser(description="Normalize Nong Sunday PixelLab animation frames")
    parser.add_argument("--pwq-root", default=None, help="Path to sunday-estate-webapp/pixel-wealth-quest")
    args = parser.parse_args()

    root = Path(args.pwq_root).expanduser() if args.pwq_root else default_pwq_root()
    counts = normalize_animation_frames(root)
    print(json.dumps(counts, ensure_ascii=False, indent=2))
    print(f"wrote {Path(root).expanduser().resolve() / 'src' / 'phaser' / 'playerAnims.ts'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
