#!/usr/bin/env python3
"""Normalize PixelLab pet (dog) animation frames for Pixel Wealth Quest.

Three dogs (`black`, `red`, `cream`) each receive PixelLab exports under
`public/assets/character/pets/gen/<id>/`. Filenames look like:

    dog-<id>_animations_<action-desc>-<hash>_south_frame_NNN.png

We:
  1. Copy each frame to a clean per-dog sequence:
     `public/assets/character/pets/anim_clean/<id>/<action>_<pixellab-dir>_NNN.png`
  2. Emit `src/phaser/petAnims.ts` for Phaser preload + register.

Actions supported (match what we generate via PixelLab):
  walk → directional, looping
  sit  → south-only, one-shot
  wag  → south-only, looping (tail wag)
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
from pathlib import Path


PET_IDS = ["black", "red", "cream"]

# PixelLab action description (after collapsing non-word chars to "_") → our short action name.
ACTION_MAP = {
    "walking_legs": "walk",
    "walking_moving": "walk",
    "sitting_down": "sit",
    "wagging_tail": "wag",
    "tail_wagging": "wag",
}
ACTION_ORDER = ["walk", "sit", "wag"]
LOOPING_ACTIONS = {"walk", "wag"}
FRAME_RATE = {"walk": 9, "sit": 7, "wag": 8}

PIXELLAB_DIRECTIONS = ["south", "south-east", "east", "north-east", "north", "north-west", "west", "south-west"]
PIXELLAB_TO_DIR8 = {
    "south": "front",
    "south-east": "front_right",
    "east": "right",
    "north-east": "back_right",
    "north": "back",
    "north-west": "back_left",
    "west": "left",
    "south-west": "front_left",
}
DIR8_ORDER = ["front", "front_right", "right", "back_right", "back", "back_left", "left", "front_left"]

PUBLIC_BASE_TMPL = "assets/character/pets/anim_clean/{id}"

FRAME_RE_TMPL = (
    r"dog-{id}_animations_(.+?)_({dirs})_frame_(\d+)\.png$"
)


def default_pwq_root() -> Path:
    if os.environ.get("PWQ_ROOT"):
        return Path(os.environ["PWQ_ROOT"]).expanduser()
    here = Path(__file__).resolve()
    # Common local layout: A-Wiki and the product repo are siblings.
    for cand in here.parents[2].parent.glob("*/pixel-wealth-quest"):
        if cand.is_dir():
            return cand
    raise SystemExit("PWQ_ROOT not set and default not found")


def action_for_slug(slug: str) -> str | None:
    """Reduce e.g. 'walking-legs-moving-in-a-walk-cycle-cute-pixel-art-dog-abc123' → 'walk'."""
    # Collapse hyphens/underscores/spaces, then take the first two words and look up.
    cleaned = re.sub(r"[\W_]+", "_", slug.lower()).strip("_")
    parts = cleaned.split("_")
    if not parts:
        return None
    # Try increasingly longer prefixes.
    for upto in (2, 3, 4):
        key = "_".join(parts[:upto])
        # Exact map match
        if key in ACTION_MAP:
            return ACTION_MAP[key]
    # Loose word match
    if "walk" in parts or "walking" in parts:
        return "walk"
    if "sit" in parts or "sitting" in parts:
        return "sit"
    if "wag" in parts or "wagging" in parts:
        return "wag"
    return None


def merge_exports_for_action(per_hash: dict[str, dict[str, list[tuple[int, Path]]]]) -> dict[str, list[tuple[int, Path]]]:
    """Union all hash buckets — pick the hash with most frames per direction.

    PixelLab often splits an 8-direction walk across multiple hashes (e.g. one
    hash holds cardinals, another holds diagonals). Picking a single hash drops
    half the directions; merging by-direction recovers the full set.
    """
    merged: dict[str, list[tuple[int, Path]]] = {}
    # For each direction, pick the hash with the highest frame count.
    all_dirs: set[str] = set()
    for by_dir in per_hash.values():
        all_dirs.update(by_dir.keys())
    for d in all_dirs:
        best: list[tuple[int, Path]] = []
        for by_dir in per_hash.values():
            if d in by_dir and len(by_dir[d]) > len(best):
                best = by_dir[d]
        if best:
            merged[d] = best
    return merged


def render_pet_anims_ts(
    per_dog_dir_anims: dict[str, dict[str, dict[str, list[str]]]],
) -> str:
    """Emit petAnims.ts.

    per_dog_dir_anims[id][action][pixellab-dir] = sorted list of relative public paths.
    """
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/game/normalize_pet_anims.py. Do not edit by hand.")
    lines.append("// PixelLab dog walk / sit / tail-wag animations for the three household pets.")
    lines.append("import type Phaser from 'phaser'")
    lines.append("import type { Dir8 } from '../types/domain'")
    lines.append("import type { PetDogId } from '../data/pets.seed'")
    lines.append("")
    lines.append('export const PET_ANIM_ACTIONS = ["walk", "sit", "wag"] as const')
    lines.append("export type PetAction = (typeof PET_ANIM_ACTIONS)[number]")
    lines.append("export const PET_MOVE_ACTIONS = [\"walk\"] as const")
    lines.append("export type PetMoveAction = (typeof PET_MOVE_ACTIONS)[number]")
    lines.append("export interface PetAnimDef { key: string; frames: readonly string[]; frameRate: number; repeat: number }")
    lines.append("")

    # PET_MOVE_ANIMS[id].walk[dir] = AnimDef
    lines.append("export const PET_MOVE_ANIMS: Record<PetDogId, Record<PetMoveAction, Partial<Record<Dir8, PetAnimDef>>>> = {")
    for dog_id in PET_IDS:
        lines.append(f"  {dog_id}: {{")
        for action in ["walk"]:
            lines.append(f"    {action}: {{")
            per_action = per_dog_dir_anims.get(dog_id, {}).get(action, {})
            for px_dir in PIXELLAB_DIRECTIONS:
                if px_dir not in per_action:
                    continue
                dir8 = PIXELLAB_TO_DIR8[px_dir]
                paths = per_action[px_dir]
                rate = FRAME_RATE[action]
                repeat = -1 if action in LOOPING_ACTIONS else 0
                key = f"pwq_pet_{dog_id}_{action}_{dir8}"
                paths_js = ", ".join(f'"{p}"' for p in paths)
                lines.append(f"      {dir8}: {{ key: '{key}', frames: [{paths_js}], frameRate: {rate}, repeat: {repeat} }},")
            lines.append("    },")
        lines.append("  },")
    lines.append("}")
    lines.append("")

    # PET_ONESHOT_ANIMS[id][action] = AnimDef (south only)
    lines.append("export const PET_ONESHOT_ANIMS: Record<PetDogId, Partial<Record<PetAction, PetAnimDef>>> = {")
    for dog_id in PET_IDS:
        lines.append(f"  {dog_id}: {{")
        for action in ["sit", "wag"]:
            per_action = per_dog_dir_anims.get(dog_id, {}).get(action, {})
            if "south" not in per_action:
                continue
            paths = per_action["south"]
            rate = FRAME_RATE[action]
            repeat = -1 if action in LOOPING_ACTIONS else 0
            key = f"pwq_pet_{dog_id}_{action}_front"
            paths_js = ", ".join(f'"{p}"' for p in paths)
            lines.append(f"    {action}: {{ key: '{key}', frames: [{paths_js}], frameRate: {rate}, repeat: {repeat} }},")
        lines.append("  },")
    lines.append("}")
    lines.append("")

    lines += [
        "export function petAnimFrameKey(dogId: PetDogId, action: PetAction, index: number, dir?: Dir8): string {",
        "  const suffix = dir ? `${dir}_${String(index).padStart(3, '0')}` : String(index).padStart(3, '0')",
        "  return `pwq_pet_anim_${dogId}_${action}_${suffix}`",
        "}",
        "",
        "export function petMoveAnimKey(dogId: PetDogId, action: PetMoveAction, dir: Dir8): string | undefined {",
        "  return PET_MOVE_ANIMS[dogId]?.[action]?.[dir]?.key",
        "}",
        "",
        "export function petOneShotAnimKey(dogId: PetDogId, action: PetAction): string | undefined {",
        "  return PET_ONESHOT_ANIMS[dogId]?.[action]?.key",
        "}",
        "",
        "export function preloadPetAnimations(scene: Phaser.Scene): void {",
        "  for (const dogId of Object.keys(PET_MOVE_ANIMS) as PetDogId[]) {",
        "    for (const action of PET_MOVE_ACTIONS) {",
        "      const byDir = PET_MOVE_ANIMS[dogId][action]",
        "      if (!byDir) continue",
        "      for (const dir of Object.keys(byDir) as Dir8[]) {",
        "        const def = byDir[dir]!",
        "        def.frames.forEach((path, index) => scene.load.image(petAnimFrameKey(dogId, action, index, dir), path))",
        "      }",
        "    }",
        "    const oneshots = PET_ONESHOT_ANIMS[dogId] ?? {}",
        "    for (const action of Object.keys(oneshots) as PetAction[]) {",
        "      const def = oneshots[action]!",
        "      def.frames.forEach((path, index) => scene.load.image(petAnimFrameKey(dogId, action, index), path))",
        "    }",
        "  }",
        "}",
        "",
        "export function registerPetAnimations(scene: Phaser.Scene): void {",
        "  for (const dogId of Object.keys(PET_MOVE_ANIMS) as PetDogId[]) {",
        "    for (const action of PET_MOVE_ACTIONS) {",
        "      const byDir = PET_MOVE_ANIMS[dogId][action]",
        "      if (!byDir) continue",
        "      for (const dir of Object.keys(byDir) as Dir8[]) {",
        "        const def = byDir[dir]!",
        "        if (scene.anims.exists(def.key)) continue",
        "        scene.anims.create({",
        "          key: def.key,",
        "          frames: def.frames.map((_, i) => ({ key: petAnimFrameKey(dogId, action, i, dir) })),",
        "          frameRate: def.frameRate,",
        "          repeat: def.repeat,",
        "        })",
        "      }",
        "    }",
        "    const oneshots = PET_ONESHOT_ANIMS[dogId] ?? {}",
        "    for (const action of Object.keys(oneshots) as PetAction[]) {",
        "      const def = oneshots[action]!",
        "      if (scene.anims.exists(def.key)) continue",
        "      scene.anims.create({",
        "        key: def.key,",
        "        frames: def.frames.map((_, i) => ({ key: petAnimFrameKey(dogId, action, i) })),",
        "        frameRate: def.frameRate,",
        "        repeat: def.repeat,",
        "      })",
        "    }",
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def normalize_pet_frames(pwq_root: str | Path) -> dict[str, dict[str, int]]:
    root = Path(pwq_root).expanduser().resolve()
    public_pets = root / "public" / "assets" / "character" / "pets"
    anim_clean_base = public_pets / "anim_clean"
    ts_out = root / "src" / "phaser" / "petAnims.ts"

    summary: dict[str, dict[str, int]] = {}
    # per_dog_dir_anims[id][action][pixellab-dir] = sorted [paths]
    per_dog_dir_anims: dict[str, dict[str, dict[str, list[str]]]] = {}

    for dog_id in PET_IDS:
        gen_dir = public_pets / "gen" / dog_id
        if not gen_dir.exists():
            continue
        # per action → per hash → per direction → list[(frame_idx, path)]
        per_action_hash: dict[str, dict[str, dict[str, list[tuple[int, Path]]]]] = {}
        frame_re = re.compile(FRAME_RE_TMPL.format(
            id=re.escape(dog_id),
            dirs="|".join(map(re.escape, PIXELLAB_DIRECTIONS)),
        ))
        for png in sorted(gen_dir.glob("*.png")):
            m = frame_re.match(png.name)
            if not m:
                continue
            slug, px_dir, idx = m.group(1), m.group(2), int(m.group(3))
            action = action_for_slug(slug)
            if action is None:
                continue
            # Use the full slug as hash bucket so different generations don't collide
            per_action_hash.setdefault(action, {}).setdefault(slug, {}).setdefault(px_dir, []).append((idx, png))

        if not per_action_hash:
            continue
        clean_dog_dir = anim_clean_base / dog_id
        clean_dog_dir.mkdir(parents=True, exist_ok=True)
        # Wipe stale clean files for this dog so renaming works idempotently
        for old in clean_dog_dir.glob("*.png"):
            old.unlink()

        per_dog_dir_anims[dog_id] = {}
        summary[dog_id] = {}
        for action, by_hash in per_action_hash.items():
            by_dir = merge_exports_for_action(by_hash)
            per_dir_paths: dict[str, list[str]] = {}
            total_frames = 0
            for px_dir, frames in by_dir.items():
                frames.sort()
                out_paths: list[str] = []
                for i, (_, src) in enumerate(frames):
                    dst_name = f"{action}_{px_dir}_{i:03d}.png"
                    dst = clean_dog_dir / dst_name
                    shutil.copy2(src, dst)
                    rel = f"{PUBLIC_BASE_TMPL.format(id=dog_id)}/{dst_name}"
                    out_paths.append(rel)
                per_dir_paths[px_dir] = out_paths
                total_frames += len(out_paths)
            per_dog_dir_anims[dog_id][action] = per_dir_paths
            summary[dog_id][action] = total_frames

    ts_text = render_pet_anims_ts(per_dog_dir_anims)
    ts_out.write_text(ts_text, encoding="utf-8")
    return summary


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pwq-root", default=str(default_pwq_root()))
    a = ap.parse_args()
    summary = normalize_pet_frames(a.pwq_root)
    print(json.dumps(summary, indent=2))
    print(f"wrote {Path(a.pwq_root).expanduser().resolve() / 'src' / 'phaser' / 'petAnims.ts'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
