#!/usr/bin/env python3
"""nightly-synthesis.py — Slice E3: distill yesterday's ledger into a
wiki context page + queue skill proposals from repeated failures.

Runs from CI (cron 20:00 UTC = 03:00 Thailand). Never mutates the ledger;
writes wiki/context/nightly-<date>.md (tracked artifact of the day).
"""
from __future__ import annotations

import json
import sys
import time
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def synthesize(ledger: Path, out_dir: Path, window_hours: int = 24,
               now: float | None = None) -> Path:
    now = now if now is not None else time.time()
    cutoff = now - window_hours * 3600
    entries = []
    if Path(ledger).is_file():
        for line in Path(ledger).read_text(encoding="utf-8").splitlines():
            try:
                e = json.loads(line)
            except json.JSONDecodeError:
                continue
            if float(e.get("ts", 0)) >= cutoff:
                entries.append(e)

    day = time.strftime("%Y-%m-%d", time.localtime(now))
    counts = Counter(e.get("type", "?") for e in entries)
    lines = [f"# Nightly Synthesis — {day}", "",
             f"> auto-generated by nightly-synthesis.py (window {window_hours}h)",
             "", "## สรุปวันนี้", ""]
    lines += [f"- **{k}**: {v} entries" for k, v in counts.most_common()]
    for kind in ("decision", "lesson", "outcome"):
        rows = [e for e in entries if e.get("type") == kind][:10]
        if rows:
            lines += ["", f"## {kind.title()}s (สูงสุด 10)", ""]
            lines += [f"- {e.get('summary', '')}" for e in rows]
    tag_counter = Counter(t for e in entries
                          for t in (e.get("tags") or []))
    hot = [t for t, c in tag_counter.most_common(8) if c >= 2]
    if hot:
        lines += ["", "## รูปแบบซ้ำ (คิด skill ใหม่ได้)", "",
                  f"แท็กที่พบซ้ำ ≥2 ครั้ง: {', '.join(hot)}",
                  "→ สั่ง `awiki skill scout` หรือ propose เมื่อเห็นจุดคุ้ม"]

    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"nightly-{day}.md"
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return out


def main() -> int:
    ledger = REPO_ROOT / ".tmp" / "memory-ledger.jsonl"
    out = synthesize(ledger, REPO_ROOT / "wiki" / "context")
    print(f"✅ {out.relative_to(REPO_ROOT)} "
          f"({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
