"""A-ROUTER generator — the routing table every agent can read.

Why this surface exists
-----------------------
Agent harnesses do not have comparable hook systems. Claude Code has six hook
events; Codex has five (no UserPromptSubmit); Gemini has two; Cline, Windsurf,
Cursor and Aider have none at all. So identical auto-pick *mechanism* across
agents is impossible, and pretending otherwise would be a lie in the docs.

What IS identical is the *data*. Every substrate reads the same ``triggers``
field through the same matcher in ``skills_registry.routing``:

    hook        Claude Code            scripts/hooks/check_a_route.py
    tool        any MCP client         MCP ``skill_route``
    model-read  everyone else          THIS FILE

This file is the third substrate. It is written to ``wiki/`` rather than
``scripts/skills_registry/generated/`` because nothing outside the repo reads
``generated/`` — the paths-only surfaces there (gen_cline, gen_windsurf, …)
contain no skill names at all. ``wiki/`` is where agent-readable brains live,
alongside SKILL-INDEX.md.

Kept deliberately small (~2k tokens). a-plan and a-debug were moved from
``invocation: both`` to ``manual`` to save ~1.2k tokens per session, so this
file is read on demand, never auto-loaded. The SessionStart stub that points
here is a separate ~200-token file.
"""
from __future__ import annotations

from .. import Registry
from .. import routing

filename = "A-ROUTER.md"

#: One-line statement of what each phase is for. Keyed by A_PHASE_CHAIN.
_PHASE_INTENT = {
    "ask":       ("ถาม / รับโจทย์",   "Restate the problem, agree done-criteria, ask before assuming."),
    "design":    ("ออกแบบ",           "Shape the solution: UX, schema, architecture, interfaces."),
    "plan":      ("วางแผน",           "Break into verifiable, independently shippable tasks."),
    "implement": ("ลงมือทำ",          "Build the thinnest slice that proves the design."),
    "review":    ("รีวิว diff",       "Read the change as an outsider before it ships."),
    "debug":     ("แก้บั๊ก",          "Reproduce, find root cause, write the failing test first."),
    "test":      ("ทดสอบ",            "Prove it works and that nothing regressed."),
}


def _fmt_triggers(triggers: list[str] | None) -> str:
    if not triggers:
        return "_(none — invoke explicitly)_"
    return " · ".join(f"`{t}`" for t in triggers)


def _is_entry_point(skill: dict) -> bool:
    """True for a top-level A-Suite skill — something a user actually invokes.

    Two things must be excluded or the table becomes noise instead of a router:
      * a-doc's 10 `types/<x>/` subskills, which a-doc dispatches internally and
        nobody calls directly. They live at skills/awiki/a-doc/types/<x>/SKILL.md
        (depth 6) rather than skills/awiki/<name>/SKILL.md (depth 4).
      * a-wiki-commands / a-wiki-telegram, which are integrations, not pipeline
        aggregators — they carry category "uncategorized".

    Accepts both layouts:
      - skills/awiki/<name>/SKILL.md   (depth 4)
      - skills/<name>/SKILL.md          (depth 3, top-level like a-rabies-report)
    """
    if skill.get("status") != "canonical":
        return False
    if not skill["name"].startswith("a-"):
        return False
    if skill.get("category") != "pipeline":
        return False
    parts = skill.get("path", "").split("/")
    # depth 3 (skills/<name>/SKILL.md) or depth 4 (skills/awiki/<name>/SKILL.md)
    if len(parts) not in (3, 4):
        return False
    # reject deeper subskill paths (e.g. skills/awiki/a-doc/types/<x>/SKILL.md = 6)
    if len(parts) == 4 and parts[1] != "awiki":
        return False
    return True


def _a_suite(registry: Registry) -> list[dict]:
    """A-Suite entry points, ordered along the phase chain then by name."""
    order = {p: i for i, p in enumerate(routing.A_PHASE_CHAIN)}
    skills = [s for s in registry.skills if _is_entry_point(s)]
    return sorted(
        skills,
        key=lambda s: (order.get(s.get("a_phase", ""), len(order)), s["name"]),
    )


def _subskill_count(registry: Registry) -> int:
    """A-* skills dispatched by a parent rather than invoked directly."""
    return sum(
        1 for s in registry.skills
        if s.get("status") == "canonical"
        and s["name"].startswith("a-")
        and not _is_entry_point(s)
    )


def render(registry: Registry) -> str:
    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/regen-skill-surfaces.py — do not edit by hand. -->",
        "<!-- Source of truth: skills-registry.json (triggers + a_phase fields). -->",
        "",
        "# A-ROUTER — intent → skill routing for every agent",
        "",
        "> **อ่านไฟล์นี้เมื่อ**: ไม่รู้ว่าจะใช้ skill ไหนกับงานที่ได้รับ",
        "> **Agents with no hook system** (Cline, Windsurf, Cursor, Aider, Kilo): this",
        "> table is your auto-pick. Match the user's request against §2, then follow §1.",
        "> **Agents with MCP**: call `skill_route` instead — same data, no reading cost.",
        "",
        "---",
        "",
        "## 1. The 7-phase spine",
        "",
        "```",
        "  ASK → DESIGN → PLAN → IMPLEMENT → REVIEW → DEBUG → TEST",
        "```",
        "",
        "งานที่ไม่ trivial เดินตาม chain นี้ — ห้ามข้ามไป IMPLEMENT ก่อนจบ ASK/DESIGN.",
        "",
        "| # | Phase | ทำอะไร | Purpose | `lifecycle_phase` ที่ป้อนเข้า |",
        "|---|-------|--------|---------|------------------------------|",
    ]
    for i, phase in enumerate(routing.A_PHASE_CHAIN, start=1):
        th, en = _PHASE_INTENT[phase]
        lifecycles = ", ".join(f"`{p}`" for p in sorted(routing.A_PHASE_TO_LIFECYCLE[phase]))
        lines.append(f"| {i} | **{phase.upper()}** | {th} | {en} | {lifecycles} |")

    lines += [
        "",
        "`lifecycle_phase` คือ vocabulary เดิมของ registry — ใช้ค้น skill เพิ่มใน",
        "[`wiki/SKILL-INDEX.md`](SKILL-INDEX.md) ได้ทุก phase",
        "",
        "---",
        "",
        "## 2. Auto-pick table",
        "",
        "เทียบ request ของ user กับ trigger ด้านล่าง — ตรงตัวไหน เรียกตัวนั้น",
        "",
        "| Skill | เรียกด้วย | Phase | Triggers |",
        "|-------|-----------|-------|----------|",
    ]
    for s in _a_suite(registry):
        hint = s.get("invocation_hint") or f"/{s['name']}"
        phase = s.get("a_phase") or "—"
        lines.append(
            f"| `{s['name']}` | `{hint}` | {phase} | {_fmt_triggers(s.get('triggers'))} |"
        )

    subskills = _subskill_count(registry)
    if subskills:
        lines += [
            "",
            f"> อีก {subskills} skill เป็น **subskill** ที่ parent เรียกเอง (เช่น `a-doc` → "
            f"`types/<type>/`) — ไม่ต้องเรียกตรง จึงไม่อยู่ในตารางนี้",
        ]

    lines += [
        "",
        "---",
        "",
        "## 3. Matching rules",
        "",
        "ใช้กฎเดียวกับ `scripts/skills_registry/routing.py` เพื่อให้ทุก agent ตัดสินเหมือนกัน:",
        "",
        "1. **ภาษาไทย = substring** — ไทยไม่มีเว้นวรรคระหว่างคำ regex `\\b` จึงใช้ไม่ได้",
        "   (`\\bแก้บั๊ก\\b` ไม่ match `ช่วยแก้บั๊กหน่อย`)",
        "2. **ASCII = ขอบหน้าเท่านั้น** — `error` match `errors` / `an error` แต่ไม่ match `terror`",
        "   (เปิดท้ายไว้ เพราะ plural/-ing/-ed ต้องติดด้วย)",
        "3. **คะแนนตามความยาว** — ≥6 ตัวอักษร = 3, 4–5 = 2, <4 = 1",
        f"4. **ผ่านเกณฑ์ที่ {routing.DEFAULT_THRESHOLD} คะแนน** — ต่ำกว่านั้นถือว่าไม่ match",
        f"5. **คืนสูงสุด {routing.DEFAULT_LIMIT} ตัว** เรียงคะแนนมาก→น้อย",
        "",
        "---",
        "",
        "## 4. ไม่ match แล้วทำยังไง",
        "",
        "| สถานการณ์ | ทำ |",
        "|-----------|-----|",
        "| ไม่มี trigger ตรงเลย | `/A-Think` — reasoning loop 7 ขั้น (fallback เสมอ ห้ามเดา) |",
        "| งานยาวข้าม session | `/A-Loop \"<objective>\"` — **เรียกเองเท่านั้น ไม่ auto** |",
        "| ต้องหลายมุมมองก่อน ship | `/A-Council` |",
        "| งานเกินความสามารถ model ปัจจุบัน | `/A-Escalate` — สร้าง prompt ส่งโมเดลที่เก่งกว่า |",
        "",
        "> `a-think` และ `a-loop` **ไม่มี trigger โดยตั้งใจ** — a-think เป็น fallback ถ้ามี",
        "> trigger จะไปแย่งงาน a-plan/a-debug; a-loop เป็น autonomous loop ข้าม session",
        "> ที่ต้องไม่เริ่มเองเพราะ keyword โผล่ใน prompt",
        "",
        "---",
        "",
        "## 5. Focus contract",
        "",
        "ระหว่างอยู่ใน phase หนึ่ง ห้ามกระโดดข้าม — ประกาศ focus แล้วเดินตาม chain:",
        "",
        "```",
        "  focus_set(skill, phase, goal)   → เริ่ม",
        "  focus_get()                     → ตอนนี้อยู่ไหน",
        "  focus_advance()                 → ไป phase ถัดไป",
        "  focus_clear()                   → จบงาน",
        "```",
        "",
        "MCP tools ชุดนี้ใช้ได้ทุก agent ที่ต่อ MCP ได้ (state: `.tmp/a-focus-<session>.json`).",
        "Claude Code เพิ่ม hook เตือนอัตโนมัติเมื่อทำงานนอก phase และตอนจบ session.",
        "",
        "---",
        "",
        f"_{len(_a_suite(registry))} A-Suite entry points"
        f"{f' (+{_subskill_count(registry)} subskills)' if _subskill_count(registry) else ''}"
        f" · spine = {' → '.join(routing.A_PHASE_CHAIN)}_",
    ]
    return "\n".join(lines) + "\n"
