"""AGENTS.md generator — emits the markdown skill-index table for AGENTS.md.

The table lists every canonical skill with its domain, lifecycle phase, and
path.  This is the human-readable "skill brain" that every agent reads at
session start.  Idempotent: same registry → identical table.
"""
from __future__ import annotations

from collections import defaultdict

from .. import Registry

filename = "skills-index.md"  # fragment; orchestrator can splice into AGENTS.md


def render(registry: Registry) -> str:
    skills = sorted(registry.canonical_for_agent("all"), key=lambda s: s["name"])
    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/regen-skill-surfaces.py — do not edit by hand. -->",
        "<!-- Source of truth: skills-registry.json. Run `python scripts/regen-skill-surfaces.py` to refresh. -->",
        "",
        "| Skill | Domain | Lifecycle | Category | Path |",
        "|-------|--------|-----------|----------|------|",
    ]
    for s in skills:
        domains = ", ".join(s.get("domain", []))
        phase = s.get("lifecycle_phase", "none")
        category = s.get("category", "")
        path = s.get("path", "")
        lines.append(f"| `{s['name']}` | {domains} | {phase} | {category} | `{path}` |")

    # Domain summary block for quick scanning.
    lines.append("")
    lines.append("## Domain Summary")
    lines.append("")
    by_domain: dict[str, int] = defaultdict(int)
    for s in skills:
        for d in s.get("domain", []):
            by_domain[d] += 1
    lines.append("| Domain | Skill count |")
    lines.append("|--------|------------|")
    for d in sorted(by_domain):
        lines.append(f"| {d} | {by_domain[d]} |")

    return "\n".join(lines) + "\n"
